name: CI/CD Pipeline to AWS ECR and EC2

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::345843269967:role/github-actions-devops
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Backend Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: devops-dashboard-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest ./backend
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Build, tag, and push Frontend Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: devops-dashboard-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest ./frontend
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
<<<<<<< Updated upstream
=======

      - name: Deploy to EC2 via AWS SSM
        run: |
          echo "Sending deployment command to EC2..."
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-075603d0a1b4e0198" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 345843269967.dkr.ecr.eu-central-1.amazonaws.com",
              "cd /home/ubuntu",
              "docker compose pull",
              "docker compose up -d",
              "docker system prune -f"
            ]' \
            --region eu-central-1 \
            --query "Command.CommandId" \
            --output text)

          echo "Command sent! Command ID: $COMMAND_ID"
          echo "Waiting for EC2 to finish deployment..."

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "i-075603d0a1b4e0198" \
            --region eu-central-1

          echo "Deployment Completed Successfully on EC2!"
>>>>>>> Stashed changes
